version: '3.8'

services:
  backend:
    build:
      context: ./Ecampus
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - e-college-network

  frontend:
    build:
      context: ./Frontend/e-college
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Access frontend at localhost:3000
    depends_on:
      - backend
    networks:
      - e-college-network

networks:
  e-college-network:
    driver: bridge
